### ISSUE TITLE
Should we merge this repo within the `shipitscript` ? 

### ISSUE THREAD

**Issue by MihaiTabara** [mozilla-releng/shipitapi#5]
with BB gone and most of operations moved to `shipitscript`, I'm wondering if it made sense to move the content of this repo under the shipitscript repo instead?

**Comment by rail** [comment]
I think we can do this. Also after v1 is gone, we can simplify the code a lot.

**Comment by MihaiTabara** [comment]
Done via https://github.com/mozilla-releng/shipitscript/pull/47
