### ISSUE TITLE
do we still need this in the Ship-it v2?

### ISSUE THREAD

**Issue by MihaiTabara** [mozilla-releng/shipitapi#9]
@rail unclear to me - do we still need this in the Ship-it v2? I haven't looked closely ever since we switched it to beta but I'm wondering if the `shipitscript` repo and this still make sense in the future world where Ship-it v1 is defunct? 

Currently shipitscript supports the:
* mark release as started
* mark release as shipped

As far as I know, first one is needed only while we still support Ship-it v1 for consistency, while second is still needed in Ship-it v1 only.

Just want to clarify - we will be able to retire this repo and the `shipitscript` counterpart when all products across all channesl will have migrated to Ship-it v2, right?

**Comment by rail** [comment]
1) We definitely don't need "mark release as started" in v2
2) "Mark release as shipped" is a bit different. We can get rid of it and a release as shipped when we schedule all the tasks in the ship phase. This will be less flexible - the "mark as shipped" step in the current implementation can be dependant on other tasks... I wonder how critical this dependency is...

**Comment by MihaiTabara** [comment]
>     1. We definitely don't need "mark release as started" in v2

Make sense.

>     2. "Mark release as shipped" is a bit different. We can get rid of it and a release as shipped when we schedule all the tasks in the ship phase. This will be less flexible - the "mark as shipped" step in the current implementation can be dependant on other tasks... I wonder how critical this dependency is...

Depends who consumes the "shipped" state. If no-one, then it's useless or can be done when we schedule all tasks as you said. If product-details or w\e consumes it, then yeah, maybe it's worth adjusting it in the graph.

**Comment by rail** [comment]
Actually we still need this. It's better to mark as shipped from an in-tree task (read shipitscript worker), so we have better control on the release timing. I'm taking care of this in #11 and probably in another followup (when v2 is no more).

**Comment by MihaiTabara** [comment]
Closed as code moved via https://github.com/mozilla-releng/shipitscript/pull/47 to shipitscript.
